In [61]:
import pandas as pd


with open('input4.txt','r') as f : 
    text = f.readlines()

lines = [x.rstrip('\n') for x in text[1:4]]
line_1 = pd.DataFrame([int(x) for x in lines[0].split(' ')]).T
line_2 = pd.DataFrame([int(x) for x in lines[1].split(' ')]).T
line_3 = pd.DataFrame([int(x) for x in lines[2].split(' ')]).T

df = pd.concat([line_1,line_2,line_3], axis =0).reset_index(drop=True)

In [62]:
import numpy as np

In [63]:
import pandas as pd


with open('input4.txt','r') as f : 
    text = f.readlines()

lines = [x.rstrip('\n') for x in text[1:4]]

In [64]:
arr1 = np.array([[int(x) for x in lines[0].split(' ')],[int(x) for x in lines[1].split(' ')],[int(x) for x in lines[2].split(' ')]])
arr1

array([[ 1, 17, 17, 19,  2, 17, 14,  6, 19, 11],
       [ 1, 19, 16,  6, 13, 15, 16, 13,  7,  2],
       [13, 11,  1,  9, 10, 12, 16, 20, 14, 12]])

In [65]:
arr1[0,0]

1

In [100]:
def algo(df, col, num) :
    if num == 1 :
        val = df[0,col] - df[2,col]
    elif num == 2 :
        val = df[0,col] - df[1,col]
    elif num == 3 :
        val = df[1,col] - df[2,col]
    elif num == 4 : 
        val = df[2,col] - df[1,col]
    elif num == 5 :
        val = df[1,col] - df[0,col]
    elif num == 6 : 
        val = df[2,col] - df[0,col]
    else : 
        val = None
    return val, num
    

In [ ]:
def next_algo(df, row, col) :
    if df[row, col-1] == 1:
        if algo(df,col,4)[0] > algo(df,col,5)[0] :
            return 
        elif algo(df,col,4)[0] < algo(df,col,5)[0] :
            return 
        else : 
            return


In [105]:
res = np.empty((2,6,10))
res[:] = np.nan
res

array([[[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]],

       [[nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan],
        [nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]]])

In [106]:
for i in range(6) : 
    res[0,i,0] = algo(arr1,0,i+1)[0]
    res[1,i,0] = algo(arr1,0,i+1)[1]

In [107]:
res

array([[[-12.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [  0.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [-12.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [ 12.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [  0.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [ 12.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]],

       [[  1.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [  2.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [  3.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [  4.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [  5.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan],
        [  6.,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]]])